export const CLOSE_MUSIC_PLAYER = 'CLOSE_MUSIC_PLAYER';
export const GET_MUSIC_PLAYLIST = 'GET_MUSIC_PLAYLIST';
export const PLAY_MUSIC_PLAYER = 'PLAY_MUSIC_PLAYER';
export const PAUSE_MUSIC_PLAYER = 'PAUSE_MUSIC_PLAYER';
