module.exports = [
    'Drake',
    'Kanye West',
    'Kendrick Lamar',
    'J. Cole',
    'A$AP Rocky',
    'Migos',
    'Lil Uzi Vert',
    'Tekashi 6ix9ine',
    'Lil Skies',
    'Future',
    'Gunna',
    'Juice WRLD',
    'Ski Mask the Slump God',
    'Post Malone',
    'YBN Nahmir',
    'YBN Cordae',
    'Lil Xan',
    'Chance the Rapper',
    'Cardi B',
    'Lil Wayne',
    'Travis Scott',
    'Lil Yachty',
    'Young Thug',
    'Lil Pump',
    'Smokepurpp',
    'Jay-Z',
    'Trippie Redd',
    'Rich the Kid',
    '21 Savage',
    'Kodak Black',
    'Kid Cudi',
    'YG',
    'Mac Miller',
    'Louis the Child',
    '070 Shake',
    'A$AP Ferg',
    'Action Bronson',
    'Beyoncé',
    'Big Sean',
    'Billie Eilish',
    'Ty Dolla $ign',
    'Buddy',
    'Lauren Jauregui',
    'Childish Gambino',
    'Chris Brown',
    'Lil Dicky',
    'J.I.D.',
    'Denzel Curry',
    'Diplo',
    'DJ Khaled',
    'Pitbull',
    'Ozuna',
    'Nicky Jam',
    'J. Balvin',
    'Flume',
    'Frank Ocean',
    'Jay Rock',
    'Jorja Smith',
    'Kaytranada',
    'Mura Masa',
    'Rex Orange County',
    'Offset',
    'Quavo',
    'Schoolboy Q',
    'Tyler the Creator',
    '6LACK',
    '2 Chainz',
    'Vince Staples',
    'Skrillex',
    'Justin Bieber'
]
