export const SEARCH_ARTISTS = 'SEARCH_ARTISTS';
export const SUCCESS_SEARCH_ARTISTS = 'SUCCESS_SEARCH_ARTISTS';
export const CLEAR_LIST_SEARCH = 'CLEAR_LIST_SEARCH';
export const SEARCH_SELECT_ARTIST = 'SEARCH_SELECT_ARTIST';
