export const GET_CONTENT_USER = 'GET_CONTENT_USER';
export const SUCCESS_GET_CONTENT_USER = 'SUCCESS_GET_CONTENT_USER';
export const FETCH_MORE_CONTENT_USER = 'FETCH_MORE_CONTENT';
export const SUCCESS_GET_TOP_TRACKS = 'SUCCESS_GET_TOP_TRACKS';
export const SUCCESS_GET_CHUNE_SUPPLY = 'SUCCESS_GET_CHUNE_SUPPLY';
export const OPEN_ARTICLE_URL = 'OPEN_ARTICLE_URL';
