export const SUCCESS_GET_USER_ARTISTS = 'SUCCESS_GET_USER_ARTISTS';
export const SUCCESS_GET_INFO_ARTIST = 'SUCCESS_GET_INFO_ARTIST';
export const FOLLOW_ARTIST = 'FOLLOW_ARTIST';
export const SUCCESS_FOLLOW_ARTIST = 'SUCCESS_FOLLOW_ARTIST';
export const UNFOLLOW_ARTIST = 'UNFOLLOW_ARTIST';
export const SUCCESS_UNFOLLOW_ARTIST = 'SUCCESS_UNFOLLOW_ARTIST';
