export { default as AboutUs } from './AboutUs';
export { default as Artist } from './Artist/Artist';
export { default as ArtistEvents } from './Events/ArtistEvents';
export { default as Artists } from './Artists/Artists';
export { default as EmailVerification } from './auth/EmailVerification';
export { default as Events } from './Events/Events';
export { default as FAQ } from './FAQ';
export { default as ForgotPassword } from './auth/ForgotPassword';
export { default as ForYou } from './ForYou';
export { HomeConnect } from './Home';
export { NavBarConnect } from './Navbar';
export { GuestNavbarConnect } from './shared/GuestNavbar';
export { default as Loading } from './shared/Loading';
export { default as Music } from './Music/Music';
export { LandingConnect } from './Landing';
export { default as News } from './News/News';
export { default as PrivacyPolicy } from './PrivacyPolicy';
export { SignInConnect } from './auth/SignIn';
export { SignUpConnect } from './auth/SignUp';
export { default as TermsOfUse } from './TermsOfUse';
export { default as Videos } from './Videos/Videos';
