export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const SUCCESS_GET_TOKEN = 'SUCCESS_GET_TOKEN';
export const SUCCESS_GET_PROFILE_SOCIAL = 'SUCCESS_GET_PROFILE_SOCIAL';
export const LOG_OUT_USER = 'LOG_OUT_USER';
